CREATE DATABASE IF NOT EXISTS SillyApp;

CREATE TABLE Login (
    NUID INT PRIMARY KEY NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Passwrd VARCHAR(30) NOT NULL,
)

CREATE TABLE Profile (
    NUID INT PRIMARY KEY NOT NULL, 
    FirstName VARCHAR(30) NOT NULL,
    LastName VARCHAR(30) NOT NULL,
    Major VARCHAR(100) NOT NULL, 
    Minor VARCHAR(100), 
    Grade int NOT NULL,
    Bio VARCHAR(150),
    HomeTown VARCHAR(30),
    Instagram VARCHAR(50),
    LookingFor VARCHAR(150),
    FOREIGN KEY (NUID) REFERENCES Login(NUID)
)

CREATE TABLE StudentClass (
    NUID INT PRIMARY KEY NOT NULL,
    ClassID INT PRIMARY KEY NOT NULL,
    FOREIGN KEY (NUID) REFERENCES Profile(NUID),
    FOREIGN KEY(ClassID) REFERENCES Class(ClassID)
)

CREATE TABLE Class (
    CLassID INT PRIMARY KEY NOT NULL,
    Title VARCHAR(50), 
    Descrip VARCHAR(150),
)
